-- Generated by fix_collapsed_products.py at 2026-03-02 20:09
-- Source product: Southern Comfort Spirit (id=63848)
-- Groups: 17 distinct products, 26 unidentified UPCs

BEGIN;

-- Update existing product 63848 -> Eagle Rare 12 Year Kentucky Straight Bourbon Whiskey
UPDATE products SET name = 'Eagle Rare 12 Year Kentucky Straight Bourbon Whiskey', slug = 'eagle-rare-12-year-kentucky-straight-bourbon-whiskey', upc = '088004030797', proof = 95, abv = 0.475, updated_at = NOW() WHERE id = 63848;

-- Remove UPCs belonging to other products from 63848
DELETE FROM product_upcs WHERE product_id = 63848 AND upc IN ('5099873015544', '1210000100641', '1210000100658', '088004026677', '088004026622', '088004026684', '088544016787', '088544019139', '088544019276', '1210000100207', '1210000100214', '1210000100283', '1210000100351', '5099873015506', '5099873016763', '088544018019', '088544018040', '088544018262', '088544018842', '088544018910', '088004026653', '088004026646', '088004026707', '1210000100719', '1210000100955', '1210000100962', '1210000100993', '088004026639', '5099873013731', '088544000014', '088004026660', '088544000021', '088544014318', '088544018941', '088544019054', '088544019160', '1210000100306', '1210000100511', '088004026691', '088544018156', '1210000100344', '088004028800');

-- Create new product records for remaining groups
WITH p1 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4163, 'Jack Daniel''s Sinatra Select', 'jack-daniels-sinatra-select', '5099873015544', 'whiskey', 'american', 'approved', 90, 0.45)
  RETURNING id),
p2 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4163, 'Paddy Blended Irish Whiskey', 'paddy-blended-irish-whiskey', '1210000100641', 'whiskey', 'american', 'approved', 80, 0.4)
  RETURNING id),
p3 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4163, 'Sazerac Straight Rye Whiskey', 'sazerac-straight-rye-whiskey', '1210000100658', 'whiskey', 'american', 'approved', 90, 0.45)
  RETURNING id),
p4 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4163, 'So Comfort', 'so-comfort', '088004026677', 'whiskey', 'american', 'approved', 80, 0.4)
  RETURNING id),
p5 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4163, 'Southern Comfort', 'southern-comfort', '088004026622', 'whiskey', 'american', 'approved', 100, 0.5)
  RETURNING id),
p6 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4163, 'Southern Comfort 100 Proof', 'southern-comfort-100-proof', '088544018019', 'whiskey', 'american', 'approved', 100, 0.5)
  RETURNING id),
p7 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4163, 'Southern Comfort 70 Proof', 'southern-comfort-70-proof', '088544018910', 'whiskey', 'american', 'approved', 70, 0.35)
  RETURNING id),
p8 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4163, 'Southern Comfort 80 Proof', 'southern-comfort-80-proof', '088004026653', 'whiskey', 'american', 'approved', 80, 0.4)
  RETURNING id),
p9 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4163, 'Southern Comfort Black', 'southern-comfort-black', '088004026646', 'whiskey', 'american', 'approved', 80, 0.4)
  RETURNING id),
p10 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4163, 'Southern Comfort Liqueur', 'southern-comfort-liqueur', '088004026639', 'whiskey', 'american', 'approved', 80, 0.4)
  RETURNING id),
p11 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4163, 'Southern Comfort Liqueur 100 Proof', 'southern-comfort-liqueur-100-proof', '088544000014', 'whiskey', 'american', 'approved', 100, 0.5)
  RETURNING id),
p12 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4163, 'Southern Comfort Original', 'southern-comfort-original', '088004026660', 'whiskey', 'american', 'approved', 80, 0.4)
  RETURNING id),
p13 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4163, 'Southern Comfort Original 80 Proof', 'southern-comfort-original-80-proof', '088004026691', 'whiskey', 'american', 'approved', 80, 0.4)
  RETURNING id),
p14 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4163, 'Southern Comfort Whiskey Liqueur 100 Proof', 'southern-comfort-whiskey-liqueur-100-proof', '088544018156', 'whiskey', 'american', 'approved', 100, 0.5)
  RETURNING id),
p15 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4163, 'Southern Comfort Whisky Liqueur', 'southern-comfort-whisky-liqueur', '1210000100344', 'whiskey', 'american', 'approved', 70, 0.35)
  RETURNING id),
p16 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status)
  VALUES (4163, 'W.L. Weller 12 Years Bourbon', 'w-l-weller-12-years-bourbon', '088004028800', 'whiskey', 'american', 'approved')
  RETURNING id),
new_upcs AS (
  INSERT INTO product_upcs (product_id, upc, size_ml, container_type, source, is_canonical)
    SELECT id, '5099873015544', 350, 'Glass Bottle', 'upc-lookup', TRUE FROM p1
  UNION ALL
    SELECT id, '1210000100641', 700, 'Glass Bottle', 'upc-lookup', TRUE FROM p2
  UNION ALL
    SELECT id, '1210000100658', 700, 'Glass Bottle', 'upc-lookup', TRUE FROM p3
  UNION ALL
    SELECT id, '088004026677', 375, 'Glass Bottle', 'upc-lookup', TRUE FROM p4
  UNION ALL
    SELECT id, '088004026622', 100, 'Glass Bottle', 'upc-lookup', TRUE FROM p5
  UNION ALL
    SELECT id, '088004026684', 200, 'Glass Bottle', 'upc-lookup', TRUE FROM p5
  UNION ALL
    SELECT id, '088544016787', 375, 'Glass Bottle', 'upc-lookup', TRUE FROM p5
  UNION ALL
    SELECT id, '088544019139', 375, 'Glass Bottle', 'upc-lookup', TRUE FROM p5
  UNION ALL
    SELECT id, '088544019276', 375, 'Glass Bottle', 'upc-lookup', TRUE FROM p5
  UNION ALL
    SELECT id, '1210000100207', 200, 'Glass Bottle', 'upc-lookup', TRUE FROM p5
  UNION ALL
    SELECT id, '1210000100214', 700, 'Glass Bottle', 'upc-lookup', TRUE FROM p5
  UNION ALL
    SELECT id, '1210000100283', 375, 'Glass Bottle', 'upc-lookup', TRUE FROM p5
  UNION ALL
    SELECT id, '1210000100351', 700, 'Glass Bottle', 'upc-lookup', TRUE FROM p5
  UNION ALL
    SELECT id, '5099873015506', 700, 'Glass Bottle', 'upc-lookup', TRUE FROM p5
  UNION ALL
    SELECT id, '5099873016763', 1000, 'Glass Bottle', 'upc-lookup', TRUE FROM p5
  UNION ALL
    SELECT id, '088544018019', 1750, 'Glass Bottle', 'upc-lookup', TRUE FROM p6
  UNION ALL
    SELECT id, '088544018040', 1000, 'Glass Bottle', 'upc-lookup', TRUE FROM p6
  UNION ALL
    SELECT id, '088544018262', 200, 'Glass Bottle', 'upc-lookup', TRUE FROM p6
  UNION ALL
    SELECT id, '088544018842', 100, 'Glass Bottle', 'upc-lookup', TRUE FROM p6
  UNION ALL
    SELECT id, '088544018910', 1750, 'Glass Bottle', 'upc-lookup', TRUE FROM p7
  UNION ALL
    SELECT id, '088004026653', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p8
  UNION ALL
    SELECT id, '088004026646', 1000, 'Glass Bottle', 'upc-lookup', TRUE FROM p9
  UNION ALL
    SELECT id, '088004026707', 50, 'Glass Bottle', 'upc-lookup', TRUE FROM p9
  UNION ALL
    SELECT id, '1210000100719', 700, 'Glass Bottle', 'upc-lookup', TRUE FROM p9
  UNION ALL
    SELECT id, '1210000100955', 700, 'Glass Bottle', 'upc-lookup', TRUE FROM p9
  UNION ALL
    SELECT id, '1210000100962', 700, 'Glass Bottle', 'upc-lookup', TRUE FROM p9
  UNION ALL
    SELECT id, '1210000100993', 50, 'Glass Bottle', 'upc-lookup', TRUE FROM p9
  UNION ALL
    SELECT id, '088004026639', 1750, 'Glass Bottle', 'upc-lookup', TRUE FROM p10
  UNION ALL
    SELECT id, '5099873013731', 1000, 'Glass Bottle', 'upc-lookup', TRUE FROM p10
  UNION ALL
    SELECT id, '088544000014', 50, 'Glass Bottle', 'upc-lookup', TRUE FROM p11
  UNION ALL
    SELECT id, '088004026660', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p12
  UNION ALL
    SELECT id, '088544000021', 50, 'Glass Bottle', 'upc-lookup', TRUE FROM p12
  UNION ALL
    SELECT id, '088544014318', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p12
  UNION ALL
    SELECT id, '088544018941', 1000, 'Glass Bottle', 'upc-lookup', TRUE FROM p12
  UNION ALL
    SELECT id, '088544019054', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p12
  UNION ALL
    SELECT id, '088544019160', 200, 'Glass Bottle', 'upc-lookup', TRUE FROM p12
  UNION ALL
    SELECT id, '1210000100306', 50, 'Glass Bottle', 'upc-lookup', TRUE FROM p12
  UNION ALL
    SELECT id, '1210000100511', 700, 'Glass Bottle', 'upc-lookup', TRUE FROM p12
  UNION ALL
    SELECT id, '088004026691', 100, 'Glass Bottle', 'upc-lookup', TRUE FROM p13
  UNION ALL
    SELECT id, '088544018156', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p14
  UNION ALL
    SELECT id, '1210000100344', 700, 'Glass Bottle', 'upc-lookup', TRUE FROM p15
  UNION ALL
    SELECT id, '088004028800', 50, 'Glass Bottle', 'upc-lookup', TRUE FROM p16
  RETURNING product_id, upc
)
SELECT product_id, upc FROM new_upcs ORDER BY upc;

-- Unidentified UPCs left on original product (review manually):
--   088004028770 (100ml)
--   088004028787 (50ml)
--   088004028794 (50ml)
--   088544014134 (1750ml)
--   088544015711 (750ml)
--   088544015735 (750ml)
--   088544016589 (1750ml)
--   088544016596 (1000ml)
--   088544016602 (750ml)
--   088544016756 (1140ml)
--   088544016763 (1000ml)
--   088544016770 (750ml)
--   088544016886 (1000ml)
--   088544016916 (750ml)
--   088544016930 (200ml)
--   088544018255 (375ml)
--   088544018286 (50ml)
--   088544019184 (500ml)
--   1210000100382 (700ml)
--   1210000100399 (50ml)
--   1210000100603 (750ml)
--   1210000100610 (750ml)
--   1210000100627 (750ml)
--   1210000100665 (1000ml)
--   1210000101044 (750ml)
--   5099873014165 (350ml)

COMMIT;