-- Generated by fix_collapsed_products.py at 2026-03-02 20:00
-- Source product: Ole Smoky Tennessee (id=64220)
-- Groups: 38 distinct products, 43 unidentified UPCs

BEGIN;

-- Update existing product 64220 -> Ole Smokey Tennessee Mason Moonshine Jar With Sippy Cup Lid Sipper
UPDATE products SET name = 'Ole Smokey Tennessee Mason Moonshine Jar With Sippy Cup Lid Sipper', slug = 'ole-smokey-tennessee-mason-moonshine-jar-with-sippy-cup-lid-sipper', upc = '804879293149', updated_at = NOW() WHERE id = 64220;

-- Remove UPCs belonging to other products from 64220
DELETE FROM product_upcs WHERE product_id = 64220 AND upc IN ('856011004151', '856011004984', '853915008995', '856011004779', '609613443640', '854628006827', '856011004052', '856011004175', '853915008438', '856011004595', '854628006926', '793573831675', '810089490964', '856011004120', '854628006056', '856011004076', '810088370434', '856011004083', '856011004885', '810088370533', '853915008285', '853915008292', '856011004021', '854628006476', '853915008261', '854628006032', '856011004045', '856011004038', '856011004861', '853915008247', '810088370267', '810088370359', '856011004212', '810088370861', '854628006674', '853915008384', '853915008421', '853915008629', '856011004878', '854628006681', '853915008797', '793573816504', '856011004014', '856011004182');

-- Create new product records for remaining groups
WITH p1 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4267, 'Ole Smoky Apple Pie', 'ole-smoky-apple-pie', '856011004984', 'whiskey', 'moonshine', 'approved', 70, 0.35)
  RETURNING id),
p2 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4267, 'Ole Smoky Banana Pudding', 'ole-smoky-banana-pudding', '853915008995', 'whiskey', 'moonshine', 'approved', 35, 0.175)
  RETURNING id),
p3 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status)
  VALUES (4267, 'Ole Smoky Big Orange', 'ole-smoky-big-orange', '856011004779', 'whiskey', 'moonshine', 'approved')
  RETURNING id),
p4 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4267, 'Ole Smoky Blackberry', 'ole-smoky-blackberry', '609613443640', 'whiskey', 'moonshine', 'approved', 40, 0.2)
  RETURNING id),
p5 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4267, 'Ole Smoky Blackberry American Whiskey', 'ole-smoky-blackberry-american-whiskey', '853915008438', 'whiskey', 'moonshine', 'approved', 60, 0.3)
  RETURNING id),
p6 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4267, 'Ole Smoky Blue Flame', 'ole-smoky-blue-flame', '856011004595', 'whiskey', 'moonshine', 'approved', 128, 0.64)
  RETURNING id),
p7 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status)
  VALUES (4267, 'Ole Smoky Buckeye', 'ole-smoky-buckeye', '854628006926', 'whiskey', 'moonshine', 'approved')
  RETURNING id),
p8 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4267, 'Ole Smoky Cherries American Whiskey', 'ole-smoky-cherries-american-whiskey', '793573831675', 'whiskey', 'moonshine', 'approved', 100, 0.5)
  RETURNING id),
p9 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status)
  VALUES (4267, 'Ole Smoky Chocolate Peanut Butter Cream', 'ole-smoky-chocolate-peanut-butter-cream', '810089490964', 'whiskey', 'moonshine', 'approved')
  RETURNING id),
p10 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status)
  VALUES (4267, 'Ole Smoky Cinnamon', 'ole-smoky-cinnamon', '856011004120', 'whiskey', 'moonshine', 'approved')
  RETURNING id),
p11 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4267, 'Ole Smoky Hunch Punch', 'ole-smoky-hunch-punch', '854628006056', 'whiskey', 'moonshine', 'approved', 80, 0.4)
  RETURNING id),
p12 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status)
  VALUES (4267, 'Ole Smoky Hunch Punch Lightnin''', 'ole-smoky-hunch-punch-lightnin', '856011004076', 'whiskey', 'moonshine', 'approved')
  RETURNING id),
p13 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4267, 'Ole Smoky Key Lime Cream', 'ole-smoky-key-lime-cream', '810088370434', 'whiskey', 'moonshine', 'approved', 35, 0.175)
  RETURNING id),
p14 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status)
  VALUES (4267, 'Ole Smoky Lemon Drop', 'ole-smoky-lemon-drop', '856011004083', 'whiskey', 'moonshine', 'approved')
  RETURNING id),
p15 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status)
  VALUES (4267, 'Ole Smoky Mandarins', 'ole-smoky-mandarins', '810088370533', 'whiskey', 'moonshine', 'approved')
  RETURNING id),
p16 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4267, 'Ole Smoky Moonshine Butter Pecan', 'ole-smoky-moonshine-butter-pecan', '853915008285', 'whiskey', 'moonshine', 'approved', 35, 0.175)
  RETURNING id),
p17 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status)
  VALUES (4267, 'Ole Smoky Moonshine Butterpecana', 'ole-smoky-moonshine-butterpecana', '853915008292', 'whiskey', 'moonshine', 'approved')
  RETURNING id),
p18 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4267, 'Ole Smoky Moonshine Cherries', 'ole-smoky-moonshine-cherries', '856011004021', 'whiskey', 'moonshine', 'approved', 100, 0.5)
  RETURNING id),
p19 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status)
  VALUES (4267, 'Ole Smoky Moonshine Peppermint', 'ole-smoky-moonshine-peppermint', '854628006476', 'whiskey', 'moonshine', 'approved')
  RETURNING id),
p20 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status)
  VALUES (4267, 'Ole Smoky Mountain Java', 'ole-smoky-mountain-java', '854628006032', 'whiskey', 'moonshine', 'approved')
  RETURNING id),
p21 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4267, 'Ole Smoky Original', 'ole-smoky-original', '856011004045', 'whiskey', 'moonshine', 'approved', 100, 0.5)
  RETURNING id),
p22 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4267, 'Ole Smoky Peach', 'ole-smoky-peach', '856011004038', 'whiskey', 'moonshine', 'approved', 40, 0.2)
  RETURNING id),
p23 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4267, 'Ole Smoky Peaches', 'ole-smoky-peaches', '856011004861', 'whiskey', 'moonshine', 'approved', 65, 0.325)
  RETURNING id),
p24 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4267, 'Ole Smoky Pickles', 'ole-smoky-pickles', '853915008247', 'whiskey', 'moonshine', 'approved', 40, 0.2)
  RETURNING id),
p25 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4267, 'Ole Smoky Pineapples with Pina Colada', 'ole-smoky-pineapples-with-pina-colada', '810088370267', 'whiskey', 'moonshine', 'approved', 40, 0.2)
  RETURNING id),
p26 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4267, 'Ole Smoky Pumpkin Spice Cream', 'ole-smoky-pumpkin-spice-cream', '810088370359', 'whiskey', 'moonshine', 'approved', 35, 0.175)
  RETURNING id),
p27 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status)
  VALUES (4267, 'Ole Smoky Shine Nog', 'ole-smoky-shine-nog', '856011004212', 'whiskey', 'moonshine', 'approved')
  RETURNING id),
p28 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status)
  VALUES (4267, 'Ole Smoky Snickerdoodle Cream', 'ole-smoky-snickerdoodle-cream', '810088370861', 'whiskey', 'moonshine', 'approved')
  RETURNING id),
p29 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status)
  VALUES (4267, 'Ole Smoky Some Beach Tennessee', 'ole-smoky-some-beach-tennessee', '854628006674', 'whiskey', 'moonshine', 'approved')
  RETURNING id),
p30 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4267, 'Ole Smoky Sour Apple', 'ole-smoky-sour-apple', '853915008384', 'whiskey', 'moonshine', 'approved', 40, 0.2)
  RETURNING id),
p31 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status)
  VALUES (4267, 'Ole Smoky Sour Razzin Berry', 'ole-smoky-sour-razzin-berry', '853915008421', 'whiskey', 'moonshine', 'approved')
  RETURNING id),
p32 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4267, 'Ole Smoky Sour Watermelon', 'ole-smoky-sour-watermelon', '853915008629', 'whiskey', 'moonshine', 'approved', 40, 0.2)
  RETURNING id),
p33 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4267, 'Ole Smoky Strawberry', 'ole-smoky-strawberry', '856011004878', 'whiskey', 'moonshine', 'approved', 65, 0.325)
  RETURNING id),
p34 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status)
  VALUES (4267, 'Ole Smoky Strawberry Mango Margarita', 'ole-smoky-strawberry-mango-margarita', '854628006681', 'whiskey', 'moonshine', 'approved')
  RETURNING id),
p35 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4267, 'Ole Smoky White Chocolate Strawberry Creme', 'ole-smoky-white-chocolate-strawberry-creme', '853915008797', 'whiskey', 'moonshine', 'approved', 35, 0.175)
  RETURNING id),
p36 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status)
  VALUES (4267, 'Ole Smoky White Lightnin''', 'ole-smoky-white-lightnin', '793573816504', 'whiskey', 'moonshine', 'approved')
  RETURNING id),
p37 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4267, 'Ole Smoky White Lightning Moonshine', 'ole-smoky-white-lightning-moonshine', '856011004182', 'whiskey', 'moonshine', 'approved', 100, 0.5)
  RETURNING id),
new_upcs AS (
  INSERT INTO product_upcs (product_id, upc, size_ml, container_type, source, is_canonical)
    SELECT id, '856011004151', 50, 'Glass Bottle', 'upc-lookup', TRUE FROM p1
  UNION ALL
    SELECT id, '856011004984', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p1
  UNION ALL
    SELECT id, '853915008995', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p2
  UNION ALL
    SELECT id, '856011004779', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p3
  UNION ALL
    SELECT id, '609613443640', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p4
  UNION ALL
    SELECT id, '854628006827', 1000, 'Glass Bottle', 'upc-lookup', TRUE FROM p4
  UNION ALL
    SELECT id, '856011004052', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p4
  UNION ALL
    SELECT id, '856011004175', 50, 'Glass Bottle', 'upc-lookup', TRUE FROM p4
  UNION ALL
    SELECT id, '853915008438', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p5
  UNION ALL
    SELECT id, '856011004595', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p6
  UNION ALL
    SELECT id, '854628006926', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p7
  UNION ALL
    SELECT id, '793573831675', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p8
  UNION ALL
    SELECT id, '810089490964', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p9
  UNION ALL
    SELECT id, '856011004120', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p10
  UNION ALL
    SELECT id, '854628006056', 50, 'Glass Bottle', 'upc-lookup', TRUE FROM p11
  UNION ALL
    SELECT id, '856011004076', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p12
  UNION ALL
    SELECT id, '810088370434', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p13
  UNION ALL
    SELECT id, '856011004083', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p14
  UNION ALL
    SELECT id, '856011004885', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p14
  UNION ALL
    SELECT id, '810088370533', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p15
  UNION ALL
    SELECT id, '853915008285', 50, 'Glass Bottle', 'upc-lookup', TRUE FROM p16
  UNION ALL
    SELECT id, '853915008292', 200, 'Glass Bottle', 'upc-lookup', TRUE FROM p17
  UNION ALL
    SELECT id, '856011004021', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p18
  UNION ALL
    SELECT id, '854628006476', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p19
  UNION ALL
    SELECT id, '853915008261', 50, 'Glass Bottle', 'upc-lookup', TRUE FROM p20
  UNION ALL
    SELECT id, '854628006032', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p20
  UNION ALL
    SELECT id, '856011004045', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p21
  UNION ALL
    SELECT id, '856011004038', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p22
  UNION ALL
    SELECT id, '856011004861', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p23
  UNION ALL
    SELECT id, '853915008247', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p24
  UNION ALL
    SELECT id, '810088370267', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p25
  UNION ALL
    SELECT id, '810088370359', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p26
  UNION ALL
    SELECT id, '856011004212', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p27
  UNION ALL
    SELECT id, '810088370861', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p28
  UNION ALL
    SELECT id, '854628006674', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p29
  UNION ALL
    SELECT id, '853915008384', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p30
  UNION ALL
    SELECT id, '853915008421', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p31
  UNION ALL
    SELECT id, '853915008629', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p32
  UNION ALL
    SELECT id, '856011004878', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p33
  UNION ALL
    SELECT id, '854628006681', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p34
  UNION ALL
    SELECT id, '853915008797', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p35
  UNION ALL
    SELECT id, '793573816504', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p36
  UNION ALL
    SELECT id, '856011004014', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p36
  UNION ALL
    SELECT id, '856011004182', 50, 'Glass Bottle', 'upc-lookup', TRUE FROM p37
  RETURNING product_id, upc
)
SELECT product_id, upc FROM new_upcs ORDER BY upc;

-- Unidentified UPCs left on original product (review manually):
--   793573814555 (750ml)
--   797734002904 (750ml)
--   810088370120 (50ml)
--   810088370144 (50ml)
--   810088370168 (50ml)
--   810088370175 (300ml)
--   810088370199 (300ml)
--   810088370243 (400ml)
--   810088370731 (750ml)
--   810088370908 (50ml)
--   810089491336 (600ml)
--   810089491497 (250ml)
--   853915008223 (1000ml)
--   853915008407 (1000ml)
--   853915008414 (1000ml)
--   853915008575 (1000ml)
--   853915008605 (750ml)
--   853915008643 (750ml)
--   853915008698 (1000ml)
--   854628006063 (750ml)
--   854628006247 (750ml)
--   854628006254 (750ml)
--   854628006308 (50ml)
--   854628006315 (300ml)
--   854628006322 (50ml)
--   854628006452 (50ml)
--   854628006490 (50ml)
--   854628006643 (50ml)
--   854628006834 (1000ml)
--   854628006889 (750ml)
--   856011004113 (750ml)
--   856011004229 (50ml)
--   856011004254 (750ml)
--   856011004267 (750ml)
--   856011004274 (750ml)
--   856011004281 (750ml)
--   856011004298 (750ml)
--   856011004328 (750ml)
--   856011004489 (1000ml)
--   856011004601 (750ml)
--   856011004663 (750ml)
--   856011004762 (750ml)
--   856011004816 (750ml)

COMMIT;