-- Generated by fix_collapsed_products.py at 2026-03-02 20:24
-- Source product: Southern Comfort Spirit (id=63848)
-- Groups: 4 distinct products, 26 unidentified UPCs

BEGIN;

-- Update existing product 63848 -> Southern Comfort
UPDATE products SET name = 'Southern Comfort', slug = 'southern-comfort', upc = '088004026653', proof = 100, abv = 0.5, updated_at = NOW() WHERE id = 63848;

-- Remove UPCs belonging to other products from 63848
DELETE FROM product_upcs WHERE product_id = 63848 AND upc IN ('088544000014', '088544018019', '088544018040', '088544018156', '088544018262', '088544018842', '088544018910', '088004026646', '088004026707', '1210000100719', '1210000100955', '1210000100962', '1210000100993');

-- Create new product records for remaining groups
WITH p1 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4163, 'Southern Comfort 100 Proof', 'southern-comfort-100-proof', '088544018156', 'whiskey', 'american', 'approved', 100, 0.5)
  RETURNING id),
p2 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4163, 'Southern Comfort 70 Proof', 'southern-comfort-70-proof', '088544018910', 'whiskey', 'american', 'approved', 70, 0.35)
  RETURNING id),
p3 AS (
  INSERT INTO products (company_id, name, slug, upc, spirit_type, spirit_subtype, approval_status, proof, abv)
  VALUES (4163, 'Southern Comfort Black', 'southern-comfort-black', '088004026646', 'whiskey', 'american', 'approved', 80, 0.4)
  RETURNING id),
new_upcs AS (
  INSERT INTO product_upcs (product_id, upc, size_ml, container_type, source, is_canonical)
    SELECT id, '088544000014', 50, 'Glass Bottle', 'upc-lookup', TRUE FROM p1
  UNION ALL
    SELECT id, '088544018019', 1750, 'Glass Bottle', 'upc-lookup', TRUE FROM p1
  UNION ALL
    SELECT id, '088544018040', 1000, 'Glass Bottle', 'upc-lookup', TRUE FROM p1
  UNION ALL
    SELECT id, '088544018156', 750, 'Glass Bottle', 'upc-lookup', TRUE FROM p1
  UNION ALL
    SELECT id, '088544018262', 200, 'Glass Bottle', 'upc-lookup', TRUE FROM p1
  UNION ALL
    SELECT id, '088544018842', 100, 'Glass Bottle', 'upc-lookup', TRUE FROM p1
  UNION ALL
    SELECT id, '088544018910', 1750, 'Glass Bottle', 'upc-lookup', TRUE FROM p2
  UNION ALL
    SELECT id, '088004026646', 1000, 'Glass Bottle', 'upc-lookup', TRUE FROM p3
  UNION ALL
    SELECT id, '088004026707', 50, 'Glass Bottle', 'upc-lookup', TRUE FROM p3
  UNION ALL
    SELECT id, '1210000100719', 700, 'Glass Bottle', 'upc-lookup', TRUE FROM p3
  UNION ALL
    SELECT id, '1210000100955', 700, 'Glass Bottle', 'upc-lookup', TRUE FROM p3
  UNION ALL
    SELECT id, '1210000100962', 700, 'Glass Bottle', 'upc-lookup', TRUE FROM p3
  UNION ALL
    SELECT id, '1210000100993', 50, 'Glass Bottle', 'upc-lookup', TRUE FROM p3
  RETURNING product_id, upc
)
SELECT product_id, upc FROM new_upcs ORDER BY upc;

-- Unidentified UPCs left on original product (review manually):
--   088004028770 (100ml)
--   088004028787 (50ml)
--   088004028794 (50ml)
--   088544014134 (1750ml)
--   088544015711 (750ml)
--   088544015735 (750ml)
--   088544016589 (1750ml)
--   088544016596 (1000ml)
--   088544016602 (750ml)
--   088544016756 (1140ml)
--   088544016763 (1000ml)
--   088544016770 (750ml)
--   088544016886 (1000ml)
--   088544016916 (750ml)
--   088544016930 (200ml)
--   088544018255 (375ml)
--   088544018286 (50ml)
--   088544019184 (500ml)
--   1210000100382 (700ml)
--   1210000100399 (50ml)
--   1210000100603 (750ml)
--   1210000100610 (750ml)
--   1210000100627 (750ml)
--   1210000100665 (1000ml)
--   1210000101044 (750ml)
--   5099873014165 (350ml)

COMMIT;